# Generated by Django 5.2.8 on 2025-12-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_transaction_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Bank', 'Bank Transfer'), ('Online', 'Online Payment')], max_length=50, null=True),
        ),
    ]
