# Generated by Django 5.2.8 on 2025-12-02 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_transaction_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='note',
        ),
        migrations.AddField(
            model_name='credit',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('UPI', 'UPI')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('UPI', 'UPI')], max_length=50, null=True),
        ),
    ]
