# Generated by Django 5.2.8 on 2025-12-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_credit_note_credit_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'CASH'), ('GPAY', 'GPAY'), ('PHONE PE', 'PHONE PE')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'CASH'), ('GPAY', 'GPAY'), ('PHONE PE', 'PHONE PE')], max_length=50, null=True),
        ),
    ]
