# Generated by Django 5.2.8 on 2025-12-04 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_credit_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='serial_no',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
