# Generated by Django 5.2.8 on 2025-12-05 05:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customer_serial_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyTurnover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_sold', models.FloatField(default=0)),
                ('total_paid', models.FloatField(default=0)),
                ('outstanding', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits', regex='^\\d{10}$')]),
        ),
    ]
