# Generated by Django 5.2.8 on 2025-12-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_monthlyturnover_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlyturnover',
            unique_together={('month', 'year')},
        ),
        migrations.AddField(
            model_name='monthlyturnover',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlyturnover',
            name='paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlyturnover',
            name='sold',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='monthlyturnover',
            name='outstanding',
        ),
        migrations.RemoveField(
            model_name='monthlyturnover',
            name='total_paid',
        ),
        migrations.RemoveField(
            model_name='monthlyturnover',
            name='total_sold',
        ),
    ]
