# Generated by Django 5.2.8 on 2025-12-05 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_product_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_before', models.IntegerField()),
                ('stock_after', models.IntegerField()),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='accounts.product')),
            ],
        ),
    ]
