# Generated by Django 5.2.8 on 2025-12-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_productstockhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstockhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
