# Generated by Django 5.2.8 on 2025-12-06 03:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20251206_0855'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
            #name='monthlyturnover',
            #unique_together={('user', 'month', 'year')},
        #),
        migrations.AlterField(
            model_name='monthlyturnover',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlyturnover',
            name='paid',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlyturnover',
            name='sold',
            field=models.FloatField(default=0),
        ),
    ]
