# Generated by Django 5.2.8 on 2025-12-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_monthlyturnover_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyturnover',
            name='profit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='customer_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='original_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
