# Generated by Django 5.2.8 on 2025-12-07 05:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_monthlyturnover_profit_product_customer_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlyturnover',
            unique_together={('user', 'month', 'year')},
        ),
    ]
