# Generated by Django 5.2.8 on 2025-12-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_monthlyturnover_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyturnover',
            name='original_cost',
            field=models.FloatField(default=0),
        ),
    ]
