# Generated by Django 5.2.8 on 2025-12-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_monthlyturnover_original_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='original_cost',
            field=models.FloatField(default=0),
        ),
    ]
