# Generated by Django 5.2.8 on 2025-12-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_usersecurity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
