# Generated by Django 5.2.8 on 2025-12-08 07:11

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_customer_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.PositiveIntegerField(default=accounts.models.generate_customer_id, unique=True),
        ),
    ]
