# Generated by Django 5.2.8 on 2025-12-09 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_customer_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='invested_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
